
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLEAR_GUESTS = 'CLEAR_GUESTS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const DEPOSIT_SUCCESS ='DEPOSIT_SUCCESS';
export const DEPOSIT_FAIL ='DEPOSIT_FAIL';
export const WITHDRAW_SUCCESS ='WITHDRAW_SUCCESS';
export const WITHDRAW_FAIL ='WITHDRAW_FAIL';
export const GETBALANCE_FAIL ='GETBALANCE_FAIL';
export const GETBALANCE_SUCCESS='GETBALANCE_SUCCESS';
export const PINCHANGE_SUCCESS = 'PINCHANGE_SUCCESS'
export const PINCHANGE_FAIL ='PINCHANGE_FAIL'

